name: deply-on-droplet

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  deploy-on-droplet:
    needs: run-tests
    runs-on: self-hosted
    steps:
      - name: check out repo on vps
        uses: actions/checkout@v2
      - name: Recreate virtual environment for real
        run: |
          cd /home
          git pull
          systemctl restart